In [1]:
#Import Libraries
import pandas as pd
import numpy as np
import os

In [2]:
path='/Users/Pc-Neumann/Desktop/Instacart Basket Analysis/02 Data/Prepared Data/df_ords_prods_merge.pkl'

In [3]:
df_prods_ords_merge=pd.read_pickle(os.path.join(path))

In [4]:
#create a smaller subset to work with
df = df_prods_ords_merge[:1000000]

In [5]:
df.shape

(1000000, 23)

In [6]:
df.head()

,Unnamed: 0_x,order_id,user_id,order_number,orders_day_of_week,order_time,days_since_prior_order,product_id,add_to_cart_order,reordered,...,aisle_id,department_id,prices,merge_indicator,price_range,price_range_loc,busiest_day,busiest_days,order_time_loc,time_of_order
0,0,2539329,1,1,2,8,NaN,196,1,0,...,77,7,9.0,both,Mid-range product,Mid-range product,Regularly busy,Regularly busy,Average Orders,Average Orders
1,0,2539329,1,1,2,8,NaN,14084,2,0,...,91,16,12.5,both,Mid-range product,Mid-range product,Regularly busy,Regularly busy,Average Orders,Average Orders
2,0,2539329,1,1,2,8,NaN,12427,3,0,...,23,19,4.4,both,Low-range product,Low-range product,Regularly busy,Regularly busy,Average Orders,Average Orders
3,0,2539329,1,1,2,8,NaN,26088,4,0,...,23,19,4.7,both,Low-range product,Low-range product,Regularly busy,Regularly busy,Average Orders,Average Orders
4,0,2539329,1,1,2,8,NaN,26405,5,0,...,54,17,1.0,both,Low-range product,Low-range product,Regularly busy,Regularly busy,Average Orders,Average Orders

In [7]:
#the groupby() function creates a pandas object (indicated by the term “object” in the output message above)
df.groupby('product_name')

In [8]:
#Apply the agg() function to each group to obtain the mean values for the “order_number” column


df.groupby('department_id').agg({'order_number': ['mean']})

              order_number
                      mean
department_id
1                14.800024
2                17.091743
3                17.913544
4                17.893092
5                15.214270
6                15.382135
7                17.694027
8                16.458105
9                15.957363
10               20.091818
11               16.482026
12               15.615061
13               16.484023
14               17.524632
15               15.691875
16               18.014071
17               16.150593
18               19.602850
19               17.631340
20               17.138607
21               21.956893

#groupby() function is being assigned to the df dataframe
Onto this resulting 'object', the agg() function 'is' applied. 
The agg() function will return the mean of the given column

In [12]:
df.groupby('department_id')['order_number'].mean()

department_id
1     14.800024
2     17.091743
3     17.913544
4     17.893092
5     15.214270
6     15.382135
7     17.694027
8     16.458105
9     15.957363
10    20.091818
11    16.482026
12    15.615061
13    16.484023
14    17.524632
15    15.691875
16    18.014071
17    16.150593
18    19.602850
19    17.631340
20    17.138607
21    21.956893
Name: order_number, dtype: float64

when using agg(), put the column you want to aggregate inside the parentheses of the agg() function as an argument. When using mean() (or any other standard aggregation function), simply index the column with square brackets, then follow it with the function you want to use after the dot

In [14]:
#Performing Multiple Aggregations

In [13]:
df.groupby('department_id').agg({'order_number': ['mean', 'min', 'max']})

              order_number
                      mean min max
department_id
1                14.800024   1  99
2                17.091743   1  98
3                17.913544   1  99
4                17.893092   1  99
5                15.214270   1  99
6                15.382135   1  99
7                17.694027   1  99
8                16.458105   1  91
9                15.957363   1  99
10               20.091818   1  99
11               16.482026   1  99
12               15.615061   1  99
13               16.484023   1  99
14               17.524632   1  99
15               15.691875   1  99
16               18.014071   1  99
17               16.150593   1  99
18               19.602850   1  99
19               17.631340   1  99
20               17.138607   1  99
21               21.956893   1  97

In [19]:
df_prods_ords_merge['max_order'] = df_prods_ords_merge.groupby(['user_id'])['order_number'].transform(np.max)

/var/folders/2g/9y11dkqx34sfytlbfh8kk9dc0000gn/T/ipykernel_95124/3157462819.py:1: FutureWarning: The provided callable <function max at 0x1059f4ea0> is currently using SeriesGroupBy.max. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "max" instead.
  df_prods_ords_merge['max_order'] = df_prods_ords_merge.groupby(['user_id'])['order_number'].transform(np.max)

 -new column called “max_order” 
 
 -the ords_prods_merge dataframe is grouped by the “user_id” column 
 
 -the transform() function is applied on the “order_number” column with the np.max argument

In [20]:
df_prods_ords_merge.head()

,Unnamed: 0_x,order_id,user_id,order_number,orders_day_of_week,order_time,days_since_prior_order,product_id,add_to_cart_order,reordered,...,department_id,prices,merge_indicator,price_range,price_range_loc,busiest_day,busiest_days,order_time_loc,time_of_order,max_order
0,0,2539329,1,1,2,8,NaN,196,1,0,...,7,9.0,both,Mid-range product,Mid-range product,Regularly busy,Regularly busy,Average Orders,Average Orders,10
1,0,2539329,1,1,2,8,NaN,14084,2,0,...,16,12.5,both,Mid-range product,Mid-range product,Regularly busy,Regularly busy,Average Orders,Average Orders,10
2,0,2539329,1,1,2,8,NaN,12427,3,0,...,19,4.4,both,Low-range product,Low-range product,Regularly busy,Regularly busy,Average Orders,Average Orders,10
3,0,2539329,1,1,2,8,NaN,26088,4,0,...,19,4.7,both,Low-range product,Low-range product,Regularly busy,Regularly busy,Average Orders,Average Orders,10
4,0,2539329,1,1,2,8,NaN,26405,5,0,...,17,1.0,both,Low-range product,Low-range product,Regularly busy,Regularly busy,Average Orders,Average Orders,10

In [ ]:
#allowing python to show more rows than in the og set up
pd.options.display.max_rows = None

In [22]:
df_prods_ords_merge.head(100)

,Unnamed: 0_x,order_id,user_id,order_number,orders_day_of_week,order_time,days_since_prior_order,product_id,add_to_cart_order,reordered,...,department_id,prices,merge_indicator,price_range,price_range_loc,busiest_day,busiest_days,order_time_loc,time_of_order,max_order
0,0,2539329,1,1,2,8,NaN,196,1,0,...,7,9.0,both,Mid-range product,Mid-range product,Regularly busy,Regularly busy,Average Orders,Average Orders,10
1,0,2539329,1,1,2,8,NaN,14084,2,0,...,16,12.5,both,Mid-range product,Mid-range product,Regularly busy,Regularly busy,Average Orders,Average Orders,10
2,0,2539329,1,1,2,8,NaN,12427,3,0,...,19,4.4,both,Low-range product,Low-range product,Regularly busy,Regularly busy,Average Orders,Average Orders,10
3,0,2539329,1,1,2,8,NaN,26088,4,0,...,19,4.7,both,Low-range product,Low-range product,Regularly busy,Regularly busy,Average Orders,Average Orders,10
4,0,2539329,1,1,2,8,NaN,26405,5,0,...,17,1.0,both,Low-range product,Low-range product,Regularly busy,Regularly busy,Average Orders,Average Orders,10
5,1,2398795,1,2,3,7,15.0,196,1,1,...,7,9.0,both,Mid-range product,Mid-range product,Regularly busy,Second least busy,Average Orders,Average Orders,10
6,1,2398795,1,2,3,7,15.0,10258,2,0,...,19,3.0,both,Low-range product,Low-range product,Regularly busy,Second least busy,Average Orders,Average Orders,10
7,1,2398795,1,2,3,7,15.0,12427,3,1,...,19,4.4,both,Low-range product,Low-range product,Regularly busy,Second least busy,Average Orders,Average Orders,10
8,1,2398795,1,2,3,7,15.0,13176,4,0,...,4,10.3,both,Mid-range product,Mid-range product,Regularly busy,Second least busy,Average Orders,Average Orders,10
9,1,2398795,1,2,3,7,15.0,26088,5,1,...,19,4.7,both,Low-range product,Low-range product,Regularly busy,Second least busy,Average Orders,Average Orders,10
10,1,2398795,1,2,3,7,15.0,13032,6,0,...,14,4.0,both,Low-range product,Low-range product,Regularly busy,Second least busy,Average Orders,Average Orders,10
11,2,473747,1,3,3,12,21.0,196,1,1,...,7,9.0,both,Mid-range product,Mid-range product,Regularly busy,Second least busy,Most Orders,Most Orders,10
12,2,473747,1,3,3,12,21.0,12427,2,1,...,19,4.4,both,Low-range product,Low-range product,Regularly busy,Second least busy,Most Orders,Most Orders,10
13,2,473747,1,3,3,12,21.0,10258,3,1,...,19,3.0,both,Low-range product,Low-range product,Regularly busy,Second least busy,Most Orders,Most Orders,10
14,2,473747,1,3,3,12,21.0,25133,4,0,...,16,8.6,both,Mid-range product,Mid-range product,Regularly busy,Second least busy,Most Orders,Most Orders,10
15,2,473747,1,3,3,12,21.0,30450,5,0,...,13,3.2,both,Low-range product,Low-range product,Regularly busy,Second least busy,Most Orders,Most Orders,10
16,3,2254736,1,4,4,7,29.0,196,1,1,...,7,9.0,both,Mid-range product,Mid-range product,Least busy,Least busy,Average Orders,Average Orders,10
17,3,2254736,1,4,4,7,29.0,12427,2,1,...,19,4.4,both,Low-range product,Low-range product,Least busy,Least busy,Average Orders,Average Orders,10
18,3,2254736,1,4,4,7,29.0,10258,3,1,...,19,3.0,both,Low-range product,Low-range product,Least busy,Least busy,Average Orders,Average Orders,10
19,3,2254736,1,4,4,7,29.0,25133,4,1,...,16,8.6,both,Mid-range product,Mid-range product,Least busy,Least busy,Average Orders,Average Orders,10
20,3,2254736,1,4,4,7,29.0,26405,5,1,...,17,1.0,both,Low-range product,Low-range product,Least busy,Least busy,Average Orders,Average Orders,10
21,4,431534,1,5,4,15,28.0,196,1,1,...,7,9.0,both,Mid-range product,Mid-range product,Least busy,Least busy,Most Orders,Most Orders,10
22,4,431534,1,5,4,15,28.0,12427,2,1,...,19,4.4,both,Low-range product,Low-range product,Least busy,Least busy,Most Orders,Most Orders,10
23,4,431534,1,5,4,15,28.0,10258,3,1,...,19,3.0,both,Low-range product,Low-range product,Least busy,Least busy,Most Orders,Most Orders,10
24,4,431534,1,5,4,15,28.0,25133,4,1,...,16,8.6,both,Mid-range product,Mid-range product,Least busy,Least busy,Most Orders,Most Orders,10
25,4,431534,1,5,4,15,28.0,10326,5,0,...,4,2.7,both,Low-range product,Low-range product,Least busy,Least busy,Most Orders,Most Orders,10
26,4,431534,1,5,4,15,28.0,17122,6,0,...,4,14.0,both,Mid-range product,Mid-range product,Least busy,Least busy,Most Orders,Most Orders,10
27,4,431534,1,5,4,15,28.0,41787,7,0,...,4,5.0,both,Low-range product,Low-range product,Least busy,Least busy,Most Orders,Most Orders,10
28,4,431534,1,5,4,15,28.0,13176,8,1,...,4,10.3,both,Mid-range product,Mid-range product,Least busy,Least busy,Most Orders,Most Orders,10
29,5,3367565,1,6,2,7,19.0,196,1,1,...,7,9.0,both,Mid-range product,Mid-range product,Regularly busy,Regularly busy,Average Orders,Average Orders,10
30,5,3367565,1,6,2,7,19.0,12427,2,1,...,19,4.4,both,Low-range product,Low-range product,Regularly busy,Regularly busy,Average Orders,Average Orders,10
31,5,3367565,1,6,2,7,19.0,10258,3,1,...,19,3.0,both,Low-range product,Low-range product,Regularly busy,Regularly busy,Average Orders,Average Orders,10
32,5,3367565,1,6,2,7,19.0,25133,4,1,...,16,8.6,both,Mid-range product,Mid-range product,Regularly busy,Regularly busy,Average Orders,Average Orders,10
33,6,550135,1,7,1,9,20.0,196,1,1,...,7,9.0,both,Mid-range product,Mid-range product,Regularly busy,Second busiest day,Most Orders,Most Orders,10
34,6,550135,1,7,1,9,20.0,10258,2,1,...,19,3.0,both,Low-range product,Low-range product,Regularly busy,Second busiest day,Most Orders,Most Orders,10
35,6,550135,1,7,1,9,20.0,12427,3,1,...,19,4.4,both,Low-range product,Low-range product,Regularly busy,Second busiest day,Most Orders,Most Orders,10
36,6,550135,1,7,1,9,20.0,25133,4,1,...,16,8.6,both,Mid-range product,Mid-range product,Regularly busy,Second busiest day,Most Orders,Most Orders,10
37,6,550135,1,7,1,9,20.0,13032,5,1,...,14,4.0,both,Low-range product,Low-range product,Regularly busy,Second busiest day,Most Orders,Most Orders,10
38,7,3108588,1,8,1,14,14.0,12427,1,1,...,19,4.4,both,Low-range product,Low-range product,Regularly busy,Second busiest day,Most Orders,Most Orders,10
39,7,3108588,1,8,1,14,14.0,196,2,1,...,7,9.0,both,Mid-range product,Mid-range product,Regularly busy,Second busiest day,Most Orders,Most Orders,10
40,7,3108588,1,8,1,14,14.0,10258,3,1,...,19,3.0,both,Low-range product,Low-range product,Regularly busy,Second busiest day,Most Orders,Most Orders,10
41,7,3108588,1,8,1,14,14.0,25133,4,1,...,16,8.6,both,Mid-range product,Mid-range product,Regularly busy,Second busiest day,Most Orders,Most Orders,10
42,7,3108588,1,8,1,14,14.0,46149,5,0,...,7,13.4,both,Mid-range product,Mid-range product,Regularly busy,Second busiest day,Most Orders,Most Orders,10
43,7,3108588,1,8,1,14,14.0,49235,6,0,...,16,1.8,both,Low-range product,Low-range product,Regularly busy,Second busiest day,Most Orders,Most Orders,10
44,8,2295261,1,9,1,16,0.0,49235,1,1,...,16,1.8,both,Low-range product,Low-range product,Regularly busy,Second busiest day,Most Orders,Most Orders,10
45,8,2295261,1,9,1,16,0.0,46149,2,1,...,7,13.4,both,Mid-range product,Mid-range product,Regularly busy,Second busiest day,Most Orders,Most Orders,10
46,8,2295261,1,9,1,16,0.0,25133,3,1,...,16,8.6,both,Mid-range product,Mid-range product,Regularly busy,Second busiest day,Most Orders,Most Orders,10
47,8,2295261,1,9,1,16,0.0,196,4,1,...,7,9.0,both,Mid-range product,Mid-range product,Regularly busy,Second busiest day,Most Orders,Most Orders,10
48,8,2295261,1,9,1,16,0.0,10258,5,1,...,19,3.0,both,Low-range product,Low-range product,Regularly busy,Second busiest day,Most Orders,Most Orders,10
49,8,2295261,1,9,1,16,0.0,12427,6,1,...,19,4.4,both,Low-range product,Low-range product,Regularly busy,Second busiest day,Most Orders,Most Orders,10
50,9,2550362,1,10,4,8,30.0,196,1,1,...,7,9.0,both,Mid-range product,Mid-range product,Least busy,Least busy,Average Orders,Average Orders,10
51,9,2550362,1,10,4,8,30.0,46149,2,1,...,7,13.4,both,Mid-range product,Mid-range product,Least busy,Least busy,Average Orders,Average Orders,10
52,9,2550362,1,10,4,8,30.0,39657,3,0,...,19,6.8,both,Mid-range product,Mid-range product,Least busy,Least busy,Average Orders,Average Orders,10
53,9,2550362,1,10,4,8,30.0,38928,4,0,...,16,12.6,both,Mid-range product,Mid-range product,Least busy,Least busy,Average Orders,Average Orders,10
54,9,2550362,1,10,4,8,30.0,25133,5,1,...,16,8.6,both,Mid-range product,Mid-range product,Least busy,Least busy,Average Orders,Average Orders,10
55,9,2550362,1,10,4,8,30.0,10258,6,1,...,19,3.0,both,Low-range product,Low-range product,Least busy,Least busy,Average Orders,Average Orders,10
56,9,2550362,1,10,4,8,30.0,35951,7,0,...,16,1.3,both,Low-range product,Low-range product,Least busy,Least busy,Average Orders,Average Orders,10
57,9,2550362,1,10,4,8,30.0,13032,8,1,...,14,4.0,both,Low-range product,Low-range product,Least busy,Least busy,Average Orders,Average Orders,10
58,9,2550362,1,10,4,8,30.0,12427,9,1,...,19,4.4,both,Low-range product,Low-range product,Least busy,Least busy,Average Orders,Average Orders,10
59,11,2168274,2,1,2,11,NaN,32792,1,0,...,19,5.2,both,Mid-range product,Mid-range product,Regularly busy,Regularly busy,Most Orders,Most Orders,14
60,11,2168274,2,1,2,11,NaN,47766,2,0,...,4,6.3,both,Mid-range product,Mid-range product,Regularly busy,Regularly busy,Most Orders,Most Orders,14
61,11,2168274,2,1,2,11,NaN,20574,3,0,...,20,2.3,both,Low-range product,Low-range product,Regularly busy,Regularly busy,Most Orders,Most Orders,14
62,11,2168274,2,1,2,11,NaN,12000,4,0,...,13,10.9,both,Mid-range product,Mid-range product,Regularly busy,Regularly busy,Most Orders,Most Orders,14
63,11,2168274,2,1,2,11,NaN,48110,5,0,...,19,2.7,both,Low-range product,Low-range product,Regularly busy,Regularly busy,Most Orders,Most Orders,14
64,11,2168274,2,1,2,11,NaN,22474,6,0,...,19,4.1,both,Low-range product,Low-range product,Regularly busy,Regularly busy,Most Orders,Most Orders,14
65,11,2168274,2,1,2,11,NaN,16589,7,0,...,19,5.0,both,Low-range product,Low-range product,Regularly busy,Regularly busy,Most Orders,Most Orders,14
66,11,2168274,2,1,2,11,NaN,35917,8,0,...,7,9.4,both,Mid-range product,Mid-range product,Regularly busy,Regularly busy,Most Orders,Most Orders,14
67,11,2168274,2,1,2,11,NaN,27344,9,0,...,20,14.8,both,Mid-range product,Mid-range product,Regularly busy,Regularly busy,Most Orders,Most Orders,14
68,11,2168274,2,1,2,11,NaN,30489,10,0,...,20,7.5,both,Mid-range product,Mid-range product,Regularly busy,Regularly busy,Most Orders,Most Orders,14
69,11,2168274,2,1,2,11,NaN,27966,11,0,...,4,4.4,both,Low-range product,Low-range product,Regularly busy,Regularly busy,Most Orders,Most Orders,14
70,11,2168274,2,1,2,11,NaN,13176,12,0,...,4,10.3,both,Mid-range product,Mid-range product,Regularly busy,Regularly busy,Most Orders,Most Orders,14
71,11,2168274,2,1,2,11,NaN,45066,13,0,...,4,2.5,both,Low-range product,Low-range product,Regularly busy,Regularly busy,Most Orders,Most Orders,14
72,12,1501582,2,2,5,10,10.0,16797,1,0,...,4,1.3,both,Low-range product,Low-range product,Regularly busy,Regularly busy,Most Orders,Most Orders,14
73,12,1501582,2,2,5,10,10.0,47526,2,0,...,16,2.0,both,Low-range product,Low-range product,Regularly busy,Regularly busy,Most Orders,Most Orders,14
74,12,1501582,2,2,5,10,10.0,8479,3,0,...,19,3.5,both,Low-range product,Low-range product,Regularly busy,Regularly busy,Most Orders,Most Orders,14
75,12,1501582,2,2,5,10,10.0,47766,4,1,...,4,6.3,both,Mid-range product,Mid-range product,Regularly busy,Regularly busy,Most Orders,Most Orders,14
76,12,1501582,2,2,5,10,10.0,19051,5,0,...,19,3.9,both,Low-range product,Low-range product,Regularly busy,Regularly busy,Most Orders,Most Orders,14
77,12,1501582,2,2,5,10,10.0,8138,6,0,...,20,2.0,both,Low-range product,Low-range product,Regularly busy,Regularly busy,Most Orders,Most Orders,14
78,13,1901567,2,3,1,10,3.0,47766,1,1,...,4,6.3,both,Mid-range product,Mid-range product,Regularly busy,Second busiest day,Most Orders,Most Orders,14
79,13,1901567,2,3,1,10,3.0,32792,2,1,...,19,5.2,both,Mid-range product,Mid-range product,Regularly busy,Second busiest day,Most Orders,Most Orders,14
80,13,1901567,2,3,1,10,3.0,20574,3,1,...,20,2.3,both,Low-range product,Low-range product,Regularly busy,Second busiest day,Most Orders,Most Orders,14
81,13,1901567,2,3,1,10,3.0,7781,4,0,...,16,6.6,both,Mid-range product,Mid-range product,Regularly busy,Second busiest day,Most Orders,Most Orders,14
82,13,1901567,2,3,1,10,3.0,28874,5,0,...,20,6.2,both,Mid-range product,Mid-range product,Regularly busy,Second busiest day,Most Orders,Most Orders,14
83,14,738281,2,4,2,10,8.0,49451,1,0,...,20,7.1,both,Mid-range product,Mid-range product,Regularly busy,Regularly busy,Most Orders,Most Orders,14
84,14,738281,2,4,2,10,8.0,32792,2,1,...,19,5.2,both,Mid-range product,Mid-range product,Regularly busy,Regularly busy,Most Orders,Most Orders,14
85,14,738281,2,4,2,10,8.0,32139,3,0,...,20,7.5,both,Mid-range product,Mid-range product,Regularly busy,Regularly busy,Most Orders,Most Orders,14
86,14,738281,2,4,2,10,8.0,34688,4,0,...,7,5.8,both,Mid-range product,Mid-range product,Regularly busy,Regularly busy,Most Orders,Most Orders,14
87,14,738281,2,4,2,10,8.0,36735,5,0,...,20,8.9,both,Mid-range product,Mid-range product,Regularly busy,Regularly busy,Most Orders,Most Orders,14
88,14,738281,2,4,2,10,8.0,37646,6,0,...,4,9.1,both,Mid-range product,Mid-range product,Regularly busy,Regularly busy,Most Orders,Most Orders,14
89,14,738281,2,4,2,10,8.0,22829,7,0,...,19,5.5,both,Mid-range product,Mid-range product,Regularly busy,Regularly busy,Most Orders,Most Orders,14
90,14,738281,2,4,2,10,8.0,24852,8,0,...,4,12.3,both,Mid-range product,Mid-range product,Regularly busy,Regularly busy,Most Orders,Most Orders,14
91,14,738281,2,4,2,10,8.0,47209,9,0,...,4,4.0,both,Low-range product,Low-range product,Regularly busy,Regularly busy,Most Orders,Most Orders,14
92,14,738281,2,4,2,10,8.0,33276,10,0,...,20,10.8,both,Mid-range product,Mid-range product,Regularly busy,Regularly busy,Most Orders,Most Orders,14
93,14,738281,2,4,2,10,8.0,45613,11,0,...,1,12.6,both,Mid-range product,Mid-range product,Regularly busy,Regularly busy,Most Orders,Most Orders,14
94,14,738281,2,4,2,10,8.0,9681,12,0,...,1,2.0,both,Low-range product,Low-range product,Regularly busy,Regularly busy,Most Orders,Most Orders,14
95,14,738281,2,4,2,10,8.0,21150,13,0,...,1,5.9,both,Mid-range product,Mid-range product,Regularly busy,Regularly busy,Most Orders,Most Orders,14
96,15,1673511,2,5,3,11,8.0,47144,1,0,...,16,14.0,both,Mid-range product,Mid-range product,Regularly busy,Second least busy,Most Orders,Most Orders,14
97,15,1673511,2,5,3,11,8.0,5322,2,0,...,19,2.9,both,Low-range product,Low-range product,Regularly busy,Second least busy,Most Orders,Most Orders,14
98,15,1673511,2,5,3,11,8.0,17224,3,0,...,19,1.6,both,Low-range product,Low-range product,Regularly busy,Second least busy,Most Orders,Most Orders,14
99,15,1673511,2,5,3,11,8.0,38656,4,0,...,19,3.4,both,Low-range product,Low-range product,Regularly busy,Second least busy,Most Orders,Most Orders,14

In [24]:
df_prods_ords_merge.loc[df_prods_ords_merge['max_order'] > 40, 'loyalty_flag'] = 'Loyal customer'

In [25]:
df_prods_ords_merge.loc[(df_prods_ords_merge['max_order'] <= 40) & (df_prods_ords_merge['max_order'] > 10), 'loyalty_flag'] = 'Regular customer'

In [26]:
df_prods_ords_merge.loc[df_prods_ords_merge['max_order'] <= 10, 'loyalty_flag'] = 'New customer'

In [27]:
df_prods_ords_merge['loyalty_flag'].value_counts(dropna=False)

loyalty_flag
Regular customer    482391
Loyal customer      322011
New customer        195598
Name: count, dtype: int64

In [28]:
df_prods_ords_merge[['user_id', 'loyalty_flag', 'order_number']].head(60)

    user_id      loyalty_flag  order_number
0         1      New customer             1
1         1      New customer             1
2         1      New customer             1
3         1      New customer             1
4         1      New customer             1
5         1      New customer             2
6         1      New customer             2
7         1      New customer             2
8         1      New customer             2
9         1      New customer             2
10        1      New customer             2
11        1      New customer             3
12        1      New customer             3
13        1      New customer             3
14        1      New customer             3
15        1      New customer             3
16        1      New customer             4
17        1      New customer             4
18        1      New customer             4
19        1      New customer             4
20        1      New customer             4
21        1      New customer             5
22        1      New customer             5
23        1      New customer             5
24        1      New customer             5
25        1      New customer             5
26        1      New customer             5
27        1      New customer             5
28        1      New customer             5
29        1      New customer             6
30        1      New customer             6
31        1      New customer             6
32        1      New customer             6
33        1      New customer             7
34        1      New customer             7
35        1      New customer             7
36        1      New customer             7
37        1      New customer             7
38        1      New customer             8
39        1      New customer             8
40        1      New customer             8
41        1      New customer             8
42        1      New customer             8
43        1      New customer             8
44        1      New customer             9
45        1      New customer             9
46        1      New customer             9
47        1      New customer             9
48        1      New customer             9
49        1      New customer             9
50        1      New customer            10
51        1      New customer            10
52        1      New customer            10
53        1      New customer            10
54        1      New customer            10
55        1      New customer            10
56        1      New customer            10
57        1      New customer            10
58        1      New customer            10
59        2  Regular customer             1